apiVersion: apps/v1
kind: Deplyment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
